# Generated by Django 2.1.7 on 2019-03-26 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=50)),
                ('taskText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftLetter', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationName', models.CharField(max_length=50)),
                ('day', models.ManyToManyField(to='rigcheckapp.Day')),
                ('shift', models.ManyToManyField(to='rigcheckapp.Shift')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rigcheckapp.Day')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rigcheckapp.Sheet')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rigcheckapp.Shift')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rigcheckapp.Station')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rigcheckapp.Shift'),
        ),
    ]
